### ISSUE TITLE
Error when calling getHeroesChain

### ISSUE THREAD

**Issue by fredcicles** [degen-heroes/dfk-hero#1]
I am trying to use your dfk-hero api.  Very nice btw.  I am getting an issue though which I not necessarily caused by your code but was wondering if you had encountered it and know the resolution.

```
heroes-helpers.ent.js:219 Uncaught (in promise) TypeError: millisecondsToMinutes is not a function
    at push../node_modules/@thanpolas/dfk-hero/src/heroes-helpers/heroes-helpers.ent.js.exports.calculateRemainingStamina (heroes-helpers.ent.js:219:1)
    at push../node_modules/@thanpolas/dfk-hero/src/heroes-fetch/normalise-blockchain.ent.js.exports.normalizeChainHero (normalise-blockchain.ent.js:146:1)
    at Array.map (<anonymous>)
    at _callee$ (fetch-heroes-blockchain.ent.js:37:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
```

I've looked in my node_modules and date-fns is there and is the version (2.28.0) in dfk-hero's package.json. 

I read 1 post were they had a similar issue that was caused by not using ; in JavaScript code; I do not use ; in my JavaScript code.  But as the error message is deep in dfk-hero code, I am not sure if it is a red herring or the actual cause somehow.

**Comment by thanpolas** [comment]
I investigated the issue and found out that it is indeed out of my control to solve this. `millisecondsToMinutes()` is a function I fetch from the date-fns package in [src/heroes-helpers/heroes-helpers.ent.js](https://github.com/degen-heroes/dfk-hero/blob/main/src/heroes-helpers/heroes-helpers.ent.js#L6).

This must have something to do with your particular setup and / or build process.
